name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true
account_id = "8a6f256451918670fbb6696590546020"

[[kv_namespaces]]
binding = "SIREN"
id = "6008b36d7fc448baa1c01966c66bc6c2"

[build]
# We are pinning this to version 0.7.2 to match your code
command = "cargo install worker-build --version 0.7.2 && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build --version 0.7.2 && worker-build --dev" }

[vars]
UUID = "14f1fd17-1ce1-4a2c-b22a-8821d37e461d"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/mayumikawai/Yumi-siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/mayumikawai/Yumi-siren/refs/heads/master/web/sub.html"
